### ISSUE TITLE
Scaffolding empty controller/view in VS 15.4.3 adds EF package references

### ISSUE THREAD

**Issue by tillig** [aspnet/Scaffolding#652]
- ASP.NET Core 2.0.0
- Visual Studio 15.4.3

If you right-click in Solution Explorer and add a controller or a view and specify it should be empty - no model, no actions, etc. - the scaffolding still adds references to:

- Microsoft.EntityFrameworkCore.Design 2.0.0
- Microsoft.EntityFrameworkCore.SqlServer 2.0.0
- Microsoft.EntityFrameworkCore.Tools 2.0.0
- Mcirosoft.VisualStudio.Web.BrowserLink 2.0.0
- Microsoft.VisualStudio.Web.CodeGeneration.Design 2.0.0.

These get added as application references, not even with `<PrivateAssets>all</PrivateAssets>` to indicate they're development dependencies instead of actual project references.

Is this expected? Could there be a way to scaffold an empty controller and/or empty view _without_ adding _any of these_?

**Comment by vijayrkn** [comment]
This is fixed.

**Comment by Davilink** [comment]
The problem is still happen in VS2019.

![image](https://user-images.githubusercontent.com/1498932/68592402-062a5d80-0461-11ea-96a3-c7b30cfaf738.png)

**Comment by vijayrkn** [comment]
@Davilink This issue is fixed in 16.4. Can you please try the latest preview version and see if you still run into this issue?

**Comment by Davilink** [comment]
@vijayrkn Yeah, it work with the preview build.

**Comment by vijayrkn** [comment]
Thanks for the confirmation. This build will be released soon.

**Comment by stijnherreman** [comment]
I'm using 16.4.5, and when scaffolding an empty controller for the first time, the following packages are added:

```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.1.1" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.10" />
```

**Comment by vijayrkn** [comment]
+ @deepchoudhery 

I think the fix is for .NET Core projects 3.0 & above. @deepchoudhery can confirm.

**Comment by deepchoudhery** [comment]
@stijnherreman in my new 16.4.5 build, I'm getting this 
![image](https://user-images.githubusercontent.com/54324771/74466522-3ad8f700-4e4c-11ea-8fd0-49fabdb791cc.png) when scaffolding an empty controller for the first time. Can you reproduce it in a new 2.1 project?

**Comment by stijnherreman** [comment]
@deepchoudhery Yes, but only when targetting .NET Framework, which happens to be what my existing project is targetting.
It does not happen when targetting .NET Core, but that is probably because the `Microsoft.AspNetCore.App` package already references the EF Core packages. Not sure where the `BrowserLink` package comes from.
